### ISSUE TITLE
Problemi con `attachment_url` di `received_documents` in API v2

### ISSUE THREAD

**Issue by lucacorti** [fattureincloud/api#161]
Da qualche settimana a questa parte i link contenuti in `attachment_url` dei `received_documents` contiene un link temporaneo firmato a un bucket S3. In alcuni casi il link punta a un bucket pubblico ed è comunque scaricabile rimuovendo gli headers di firma, in altri invece punta a un file non pubblicamente accessibile. Per gli `issued_documents` invece viene sempre restituito un link diretto sempre accessibile.

 In precedenza i link erano tutti direttamente accessibili. Si tratta di una modifica intenzionale oppure di un cambio involontario?
Potete chiarire quali sono le modalità con cui chi si integra alle API dovrebbe accedere ai file?
Questi link vanno considerati sempre temporanei o permanenti?

**Comment by valmoz** [comment]
Buongiorno,
sì, è stata effettuata una modifica, per cui ora i link ai documenti saranno temporanei. Vi consigliamo di considerare sempre i link come temporanei e di non memorizzarli, in quanto non saranno più validi dopo la scadenza.

Cercheremo di comunicare in maniera più efficace le modifiche di questo tipo nel futuro.

A disposizione per ulteriori domande
Mauro
