### ISSUE TITLE
Problema DELETE su Prima Nota, errore 409

### ISSUE THREAD

**Issue by Drakas** [fattureincloud/api#210]
### Discussed in https://github.com/fattureincloud/api/discussions/194

<div type='discussions-op-text'>

<sup>Originally posted by **Drakas** December 15, 2022</sup>
Buonasera,

Non mi è possibile cancellare una voce da primanota. Dato l'id come da documentazione, ottengo il seguente errore:
**{"error":{"message":"Cannot perform the operation."}}**

E, dai log di Fatture in Cloud, ottengo: 

**DELETE | c/xxxxxx/cashbook/147xxxxx | 409**
Le x le ho inserite per anonimizzare. 

L'ID è corretto, ho anche controllato per sicurezza ed è anche identico a quando ispeziono la richiesta via browser del pannello di fatture in cloud: 
**https://secure.fattureincloud.it/edit_primanota.php?id=147xxxxx**

A cosa potrebbe essere dovuto?
Grazie e buona serata</div>

**Comment by emajo** [comment]
Ciao @Drakas abbiamo rilasciato ieri il fix!
