### ISSUE TITLE
Sconti su imponibile fattura 

### ISSUE THREAD

**Issue by procnedev** [fattureincloud/api#223]
Salve a tutti,
    mi collego a questa discussione per capire se è possibile utilizzare la combinazione "amount_due_discount" + "discount_highlight" per gestire lo sconto sull'imponibile. Cosa che al momento, dopo una serie di prove, non mi è chiara.

Come devono essere compilati rispettivamente i campi:

- amount_net (importo al netto oppure al lordo dello sconto?)
- amount_vat (iva calcolata sull'importo al netto oppuer al lordo dello sconto?)
- amount_due_discount (valore dello sconto sull'imponibile?)

l'endpoint al momento ci ritorna il messaggio:
"{\"error\":{\"message\":\"Il totale dei pagamenti non corrisponde al totale da pagare.\",\"validation_result\":null}}"

Grazie.

### Discussed in https://github.com/fattureincloud/api/discussions/107

<div type='discussions-op-text'>

<sup>Originally posted by **donlegro** October  6, 2022</sup>
Salve a tutti,
il campo discount accetta solo valori numeri quindi vorrei sapere come gestire multi sconto tipo: 10+5, 5+5+5, ecc.

Inoltre volevo sapere  come gestire uno sconto o maggiorazione (ma soprattutto maggiorazione) con prezzo netto invece di percentuale.
Posso usare ei_raw -> DettaglioLinee -> ScontoMaggiorazione... per quanto riguarda il tracciato xml ma c'è una corrispondenza anche con i campi di Fatture in cloud?

Infine volevo capire l'utilità di discount_highlight che nella prima versione si chiamava sconto_rosso.
Grazie in anticipo per le risposte.</div>

**Comment by emajo** [comment]
Ciao @procnedev, facciamo un po' di chiarezza.
All'interno di ogni item di una fattura abbiamo il campo `amount_net` che si riferisce al prezzo netto prima di eventuale sconto.
Per aggiungere uno sconto sempre all'interno di ogni item abbiamo il campo `discount` ovvero lo sconto percentuale sul netto.
Una volta applicato lo sconto al prezzo netto viene calcolata l'iva, per specificare l'iva abbiamo il campo `vat.id`, ad esempio l'iva al 22% ha id 0.
I campi `discount_highlight` e `amount_due_discount` sono invece relativi alla fattura in generale, non al singolo item, `amount_due_discount` è uno sconto/maggiorazione (a seconda del segno che si passa) che viene applicato sul totale della fattura (ovvero sulla somma di tutti i prezzi ivati degli items), mentre `discount_highlight` fa semplicemente apparire sul pdf della fattura una scritta in rosso con lo sconto applicato.
Consiglio comunque di leggere questa [guida](https://developers.fattureincloud.it/docs/guides/invoice-creation) per la creazione di fatture, mentre [questa](https://developers.fattureincloud.it/docs/guides/invoice-totals) è specifica sul calcolo dei totali.

Chiudo questa issue in quanto non si tratta appunto di una issue ma di dubbi sul funzionamento delle api, se dovessero servire altri chiarimenti chiedo gentilmente di aprire una discussion.

Grazie,
Emanuele.
