### ISSUE TITLE
Buongiorno,

### ISSUE THREAD

**Issue by SupervisoreOP** [fattureincloud/api#227]
Buongiorno,
vi chiedo gentilmente un supporto:

Sto creando una chiamata API per creare ORDINI/FATTURE

EsempiO:
```
{
"data": {
"type": "invoice",
"amount_net": 0,
"amount_due_discount": 0,
"entity": {
"id": 0,
"name": "NOME",
"tax_code": "CF",
"address_street": "INDIRIZZO",
"address_postal_code": "CAP",
"address_city": "CITTA",
"address_province": "PROVINCIA",
"address_extra": "",
"country": "Italia",
"email": "test@test.it",
"phone": "3317823711"
"certified_email": ""
},
```
Premettendo che non passo nessun ID_ENTITY in quanto non voglio censire il cliente (e non c'è l'ho già censito), tutto funziona ma le uniche cose che non appaiono sono EMAIL & PHONE. Perchè?

Ho provato invece a impostare una chiamata precedente alla creazione della fattura, per creare il cliente, passando poi l'ID_ENTITY alla successiva call di creazione documento, e in questo caso mi appare email e phone.

Leggendo però le linee guida, c'è scritto di inserire l'id_entity solo se il cliente esiste, allora seguo la linea guida:
_If the customer is most likely a one-time customer, you can just insert his details directly in the invoice._

Come posso far apparire nel PDF creato email e phone, del cliente che sto passando (senza doverlo censire)?

Grazie a tutti

_Originally posted by @SupervisoreOP in https://github.com/fattureincloud/api/discussions/226_

**Comment by valmoz** [comment]
Chiudo perché questa non è una issue ma una richiesta di general guidance che dovrebbe essere gestita tramite discussion. 
Stiamo già fornendo supporto sulla [discussion](https://github.com/fattureincloud/api/discussions/226) duplicata, quindi non ha senso tener aperta anche questa issue.

Grazie
Mauro
