### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by Mattia-Marchiorato** [fattureincloud/api#269]
**Describe the bug**
call the api on endpoint get [504] Server error:

**To Reproduce**
[504] Server error: `GET https://api-v2.fattureincloud.it/c/999999/info/vat_types` resulted in a `504 Gateway Time-out`

We receive this error in production, customers can't checkout and pay because of this 504 also on listDetailedCountries.

**Comment by valmoz** [comment]
Buongiorno @Mattia-Marchiorato 
il problema sul server dovrebbe essere stato risolto.

Per questo genere di problemi, specialmente se avvengono nel weekend, la prossima volta vi consiglio di contattare il supporto clienti.

Grazie
Mauro

**Comment by Mattia-Marchiorato** [comment]
Salve @valmoz ,

Come detto stiamo usando le API in produzione, errori sui vostri endpoint causano alla nostra società un danno economico (gli utenti non potevano fare checkout ricevendo un 5** error) e di immagine poiché la nostra piattaforma era parzialmente offline. Non è il primo episodio, vi chiediamo quindi se avete un piano per evitare che questo ed altri episodi segnalati in passato non si verifichino.
- documentazione errata
- breaking changes non comunicati 
- bug sui dati (iso per countries)
- errori 5**
