### ISSUE TITLE
Add more informations to entity while fetching received_documents

### ISSUE THREAD

**Issue by TommyMoscatelli** [fattureincloud/api#281]
At the moment, while fetching received_documents only two fields of the entity object are returned. These two fields are id and name.

Could be useful to get all the informations about the entity, just like you did for the issued_documents. In this way I can avoid to do two different API calls.

**Comment by emajo** [comment]
Hi @TommyMoscatelli, I just tried and the returned entity fields inside a received document are:
``` 
  "id": null,
  "name": "",
  "address_street": "",
  "address_postal_code": "",
  "address_city": "",
  "address_province": "",
  "country": "",
  "vat_number": "",
  "tax_code": ""
```
Could you share the response you are receiving? It seems strange that you are not getting the other fields.

Thanks,
Emanuele.

**Comment by TommyMoscatelli** [comment]
Yes, I'm receiving the other fields, but they are always empty.
For example, this supplier is saved with a vat_number and a tax_code, but when I try to fetch his received_documents, I can see only id and name.

```
"entity": {
			"id": 98774XX,
			"name": "NAME AND SURNAME",
			"address_street": "",
			"address_postal_code": "",
			"address_city": "",
			"address_province": "",
			"country": "",
			"vat_number": "",
			"tax_code": ""

```

**Comment by emajo** [comment]
Are you sure that the other fields are actually set? From my tests if the are set correctly in the supplier they are returned accordingly in the get received documents api call, I suggest to contact our customer support to receive more specific support so we can see if there is actually somethng wrong checking the documents and suppliers ids.
