### ISSUE TITLE
Errore durante modifica Cliente (PUT)

### ISSUE THREAD

**Issue by Drakas** [fattureincloud/api#316]
Buona sera, non riesco a modificare alcun cliente già creato in precedenza. 
Come da documentazione API : 
https://developers.fattureincloud.it/api-reference#put-/c/-company_id-/entities/clients/-client_id-

Effettuo una richiesta PUT che posso visionare anche nei log del backend di fatture in cloud
PUT | c/xxxxxx/entities/clients/xxxxxx51 | 409 | 2023-05-07 xx:46:38

Tuttavia, al posto di modificare correttamente il cliente (nel mio caso, tentavo di modificare il "type"), ottengo il seguente errore:
"error":{"message":"Esiste gi\u00e0 un cliente  con lo stesso codice (xxxxx xx xxxxxxx)."

Ritengo che non abbia alcun senso questo messaggio in una azione di modifica, anzi, deve esiste un codice per essere modificato. E tale errore non mi permette di applicare le modifiche presenti nel body della richiesta come vorrei.

Vi risulta la stessa cosa?

Grazie mille e a presto

**Comment by emajo** [comment]
Ciao @Drakas, per indagare più a fondo la problematica riscontrata abbiamo bisogno della chiamata effettiva che sta cercando di fare e degli id delle risorse in questione, per questo motivo le consiglio di contattare il nostro supporto dalla pagina di Fatture in Cloud in modo da essere in grado di fornirle il supporto necessario.

Grazie,
Emanuele.
