### ISSUE TITLE
Ask for payments_list and items_list on issued_documents results in error response

### ISSUE THREAD

**Issue by horsep0wa** [fattureincloud/api#325]
**Describe the bug**
Asking for `payments_list` and `items_list` fields on `issued_documents` resources results in an error response.
The same fields are instead available if requested as `fieldset=detailed`

**To Reproduce**
```
curl -X GET "https://api-v2.fattureincloud.it/c/{id}/issued_documents?type=order&fields=payments_list" \
 -H "accept: application/json"\
 -H "authorization: Bearer {token}"
```
```
curl -X GET "https://api-v2.fattureincloud.it/c/{id}/issued_documents?type=order&fields=items_list" \
 -H "accept: application/json"\
 -H "authorization: Bearer {token}"
```
Response:
`{"error":{"message":"An unexpected error occurred. Contact support for more information."}}`

**Expected behavior**
You can query for `payment_list` and `items_list` without the need of a detailed large payload

**Comment by emajo** [comment]
Hi, @horsep0wa, for this kind of issues I suggest to open a discussion as it can be useful even for other users, regarding your problem we will look into it but for now it can be resolved by adding an additional field such as the id like this:
```
curl -X GET "https://api-v2.fattureincloud.it/c/{id}/issued_documents?type=order&fields=id,payments_list" \
 -H "accept: application/json"\
 -H "authorization: Bearer {token}"
```

Thanks,
Emanuele.
