### ISSUE TITLE
502 server error

### ISSUE THREAD

**Issue by Mattia-Marchiorato** [fattureincloud/api#364]
**Describe the bug**
On a 
PUT https://api-v2.fattureincloud.it/c/1234/entities/clients/1234
resulted in a 502 Bad Gateway

This is a bug in production, please fix it as soon as possibile.

Thanks

MM

**Comment by valmoz** [comment]
Hi Mattia,
we're already working on it.

Mauro

**Comment by Mattia-Marchiorato** [comment]
Grazie Mauro,

Però queste API sono in produzione, trovo gravi questi disservizi (se ben ti ricordi questa è forse la quarta volta che capitano problemi), essendo (più o meno) colleghi trovo sincerammente poco spiegabile ed inammissibile questi errori. Abbiamo clienti che non riescono a pagare perchè bloccati da questa problematica, scusa lo sfogo ma stiamo perdendo credibilità con i nostri clienti e soldi.

MM

**Comment by valmoz** [comment]
Buongiorno Mattia,
come sicuramente ben sa, essendo un collega, i bug sono comuni ed è impossibile evitarli tutti.
Anche aziende molto più grandi e con più mezzi di noi come Google o Amazon sono soggette a dei bug sporadici, quello che conta di più è la velocità con cui si reagisce a queste problematiche. Le assicuro che il nostro team infrastrutturale sta già lavorando per risolvere il problema, che al momento sta impattando tutta la nostra user base.
Ciò non significa che i disservizi siano accettabili, cerchiamo sempre per quanto possibile di migliorare le nostre procedure per minimizzare il più possibile l'incidenza di tali problemi.

Per quanto riguarda i problemi di credibilità, mi creda al momento siamo noi i primi ad essere sotto i riflettori. Sono sicuro che i colleghi stiano facendo del loro meglio per ripristinare la funzionalità.

Riapro la issue e la tengo aggiornato.
Grazie
Mauro

**Comment by Mattia-Marchiorato** [comment]
Buongiorno Mauro,

Le mie vogliono essere critiche costruttive al fine di avere un servizio utilizzabile, sicuramente i bug sono comuni ma forse dovreste investire più tempo e risorse sul processo di testing prima della messa online di nuove features o sull'affidabilità dei vostri sistemi, un errore 5xx come saprai è da considerarsi abbastanza grave ed inevitabilmente blocca il nostro processo di checkout del cliente, forse potrebbero essere gestite diversamente le risposte degli endpoint per evitare queste problematiche.

Saluti

MM

**Comment by valmoz** [comment]
Prenderemo in considerazione le sue osservazioni.
Il problema comunque sembra essere rientrato al momento, ci faccia sapere.

Grazie
Mauro

**Comment by Mattia-Marchiorato** [comment]
Possiamo darci del tu se per te va bene, si ti confermo che ora l'endpoint risponde correttamente.
Chiudo l'issue.

Saluti

MM
