### ISSUE TITLE
Data pagamento in DDT

### ISSUE THREAD

**Issue by FrantZ1971** [fattureincloud/api#417]
Inserendo la data di pagamento non viene valorizzata: forse non è possibile valorizzarla sul documento DDT
Questo il messaggio inviato
{
    "data": {
        "type": "delivery_note",
        "use_gross_prices": false,
        "number": 19944,
        "date": "2023-06-29",
        "entity": {
            "id": 19944,
            "name": "XXX",
            "address_street": "XXX",
            "address_postal_code": "XXX",
            "address_city": "XXX",
            "address_province": "XX",
            "code": "XXX",
            "vat_number": "XXXXXXXX"
        },
        "items_list": [
            {
                "code": "885",
                "name": "XXX",
                "qty": 60,
                "net_price": 12.5,
                "discount": 10.0
            }
        ],
        "payments_list": [
            {
                "due_date": "2024-02-18",
                "amount": 675,
                "status": "not_paid"
            }
        ]
    }
}

**Comment by emajo** [comment]
Ciao @FrantZ1971, per dei prossimi questiti la sezione corretta è quella delle discussions, in questo caso comunque la data viene settata ma nel campo `dn_date` non `date`, controllando quel campo dovrebbe risultare corretto.

Grazie,
Emanuele.
