### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Mattia-Marchiorato** [fattureincloud/api#421]
Hello,

we receive a 502 Bad Gateway on
GET https://api-v2.fattureincloud.it/c/12345/info/payment_accounts 

Is there any problem? Do you have a status page for the api?

Thanks

MM

**Comment by valmoz** [comment]
Hi @Mattia-Marchiorato 
yes, we had some problems with production infrastructure. Now it should be recovered. 
Let us know if you're still facing this issue.

Mauro
