### ISSUE TITLE
Come impostare il Calcolo Inverso in Zapier?

### ISSUE THREAD

**Issue by angelarted** [fattureincloud/api#439]
### Discussed in https://github.com/fattureincloud/api/discussions/438

<div type='discussions-op-text'>

<sup>Originally posted by **angelarted** April 16, 2024</sup>
Ciao,
mi manca solo un ultimo step per finalizzare la scrittura automatica delle fatture ad ogni acquisto fatto dalla piattaforma di e-learning: impostare il calcolo inverso.
Purtroppo non riesco a trovare nei vari campi che Zapier mi chiede di compilare, la voce corrispondente.
Anche nella documentazione di come scrivere una invoice non lo vedo ( [qui](https://developers.fattureincloud.it/docs/guides/invoice-creation) )
Potete gentilmente aiutarmi?

Grazie,

Simona</div>

**Comment by valmoz** [comment]
già risposto in https://github.com/fattureincloud/api/discussions/438, chiudo
