### ISSUE TITLE
Record duplicati in response issued_documents

### ISSUE THREAD

**Issue by claudiocnc** [fattureincloud/api#460]
In determinate condizioni alcune righe della response risultano duplicate, come se l'ultima fattura della pagina corrente venga sostituita con la prima fattura della pagina successiva.
Questo avviene nello specifico usando come sorting = date e fieldset = detailed

`curl --location 'https://api-v2.fattureincloud.it/c/company_id/issued_documents?type=invoice&sort=date&fieldset=detailed&per_page=5&page=1'`

il problema non si presenta usando come sorting il campo id.

**Comment by emajo** [comment]
Ciao @claudiocnc, questo è dovuto al fatto che se ci sono delle fatture con la stessa data queste vengono recuperate in un ordine che può variare per ogni query, quello che consiglio è aggiungere un secondo criterio di ordinamento per far sì che l'ordine sia sempre consistente, in questo caso consiglierei l'id, quindi `sort=date,id`.

Grazie,
Emanuele.

**Comment by emajo** [comment]
Per le prossime problematiche le chiedo di aprire una discussion al posto delle issues in modo da essere trovata più facilmente anche dagli altri utenti.

Grazie,
Emanuele.
