### ISSUE TITLE
Campi IntentDeclarationProtocolNumber e IntentDeclarationProtocolDate con tipo errato

### ISSUE THREAD

**Issue by deppa88** [fattureincloud/api#48]
I campi IntentDeclarationProtocolNumber e IntentDeclarationProtocolDate risultano di tipo errato. 
Infatti il campo IntentDeclarationProtocolNumber è dichiarato di tipo DateTime? mentre dovrebbe essere di tipo String e il campo IntentDeclarationProtocolDate è dichiarato di tipo String mentre dovrebbe essere di tipo DateTime?.

Questo comporta un errore in fase di deserializzazione dei dati nelle chiamate GetReceivedDocument e GetIssuedDocument nel caso in cui quei dati siano presenti nel documento, facendo sì che il risultato di tale chiamata ritorni sempre null.

**Comment by emajo** [comment]
Ciao @deppa88 abbiamo appena rilasciato una nuova versione per tutte le sdk che contiene il fix per i campi IntentDeclarationProtocolNumber e IntentDeclarationProtocolDate.

grazie per la segnalazione,
Emanuele
